apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: supabase
  namespace: flux-system
spec:
  values:
    # Azure-specific persistence configuration
    db:
      persistence:
        size: 32Gi
        storageClassName: supabase-premium-rwo
    
    storage:
      persistence:
        size: 20Gi
        storageClassName: supabase-premium-rwo
    
    imgproxy:
      persistence:
        size: 10Gi
        storageClassName: supabase-premium-rwo
    
    # Azure-optimized resource settings
    db:
      resources:
        requests:
          cpu: "500m"
          memory: "1Gi"
        limits:
          cpu: "2000m"
          memory: "4Gi"
    
    studio:
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"
    
    auth:
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"
    
    rest:
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"
    
    realtime:
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"
    
    meta:
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"
    
    storage:
      resources:
        requests:
          cpu: "200m"
          memory: "512Mi"
        limits:
          cpu: "1000m"
          memory: "1Gi"
    
    imgproxy:
      resources:
        requests:
          cpu: "200m"
          memory: "512Mi"
        limits:
          cpu: "1000m"
          memory: "2Gi"
    
    # Kong configuration for Azure
    kong:
      resources:
        requests:
          cpu: "200m"
          memory: "512Mi"
        limits:
          cpu: "1000m"
          memory: "1Gi"
      
      # Change to ClusterIP for ingress routing
      service:
        type: LoadBalancer
      
      # Enable ingress for Azure
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: "100m"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
          nginx.ingress.kubernetes.io/enable-cors: "true"
          nginx.ingress.kubernetes.io/cors-allow-origin: "*"
          nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
          nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,apikey,x-client-info"
          # Disable global rewrite to prevent conflicts with other ingresses
          nginx.ingress.kubernetes.io/rewrite-target: ""
        hosts:
          - paths:
              - path: /auth
                pathType: Prefix
    
    # Additional Azure-specific environment variables
    db:
      environment:
        # Azure-specific performance tuning
        POSTGRES_MAX_CONNECTIONS: "200"
        POSTGRES_SHARED_BUFFERS: "256MB"
        POSTGRES_EFFECTIVE_CACHE_SIZE: "1GB"
        POSTGRES_WORK_MEM: "4MB"
    
    # Functions configuration for Azure
    functions:
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"
